apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-a
  namespace: localai-benchmark
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - genai-pb-worker-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-b
  namespace: localai-benchmark
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - genai-pb-worker-02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-c
  namespace: localai-benchmark
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - genai-pb-worker-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-d
  namespace: localai-benchmark
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - genai-pb-worker-02
