apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/topology
components:
  - ../../../overlays/topology/placement/spread-genai-pb-3-worker-nodes
  - ../../../overlays/topology/worker-count/w4
