apiVersion: v1
kind: Namespace
metadata:
  name: genai-tenant-a
  labels:
    mon-agent/enabled: 'true'
    istio-injection: enabled
    localai.benchmark/tenant: tenant-a
    localai.benchmark/scheduler-mode: loadaware-scheduler
    localai.benchmark/traffic-access-mode: gateway-routed
