apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-a
  namespace: localai-benchmark
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-b
  namespace: localai-benchmark
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-c
  namespace: localai-benchmark
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai-rpc-d
  namespace: localai-benchmark
spec:
  replicas: 0
