apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/topology
components:
  - ../../../overlays/topology/placement/colocated-sc-app-02
  - ../../../overlays/topology/worker-count/w3
