apiVersion: v1
kind: Namespace
metadata:
  name: genai-tenant-c
  labels:
    mon-agent/enabled: 'true'
    istio-injection: enabled
    localai.benchmark/tenant: tenant-c
    localai.benchmark/scheduler-mode: networkaware-scheduler
    localai.benchmark/traffic-access-mode: gateway-routed
