apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genai-tenant-b
resources:
  - namespace.yaml
  - ../../../base/foundation/storage
  - ../../../base/shared/rpc-workers-services
  - ../../../base/topology
  - ../../../overlays/server/models/m1
components:
  - ../../../overlays/topology/worker-count/w2
patches:
  - path: patch-default-scheduler-labels.yaml
