apiVersion: v1
kind: Service
metadata:
  name: localai-rpc-a
  namespace: genai-thesis
spec:
  selector:
    app: localai-rpc-a
  ports:
    - name: rpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: localai-rpc-b
  namespace: genai-thesis
spec:
  selector:
    app: localai-rpc-b
  ports:
    - name: rpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: localai-rpc-c
  namespace: genai-thesis
spec:
  selector:
    app: localai-rpc-c
  ports:
    - name: rpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: localai-rpc-d
  namespace: genai-thesis
spec:
  selector:
    app: localai-rpc-d
  ports:
    - name: rpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
